import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>CV Bayu Krisna</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main>
      <nav className='p-5 bg-white shadows flex justify-between items-center w-[50%]'>
        <div className='top-0'>
          <span className='text-2x1 font-[Poppins] cursor-pointer'>
           CV
          </span>
        </div>
        <ul className='flex md:items-center'>
          <li className='mx-4'>
            <a href='#About Me' className='text-1xl text -skew-x-1 hover:text duration-500'>About Me</a>
          </li>
          <li className='mx-4'>
            <a href='#Pendidikan' className='text-1xl text -skew-x-1 hover:text duration-500'>Pendidikan</a>
          </li>
          <li className='mx-4'>
            <a href='#Keahlian' className='text-1xl text -skew-x-1 hover:text duration-500'>Keahlian</a>
          </li>
          <li className='mx-4'>
            <a href='#Contact' className='text-1xl text -skew-x-1 hover:text duration-500'>Contact</a>
          </li>
        </ul> 
      </nav>  
      <div>
      <div className=' flex justify-center items-center w-[50%] h-[100vh] ml-auto bg-gradient-to-r from-violet-500 to-fuchsia-500'>
        <img className='w-[60%] h-[70%]' src='WhatsApp Image 2023-01-26 at 10.05.58.jpg'></img>
      </div>
      </div>
      <nav className='w-[50%]'>
      <div className='flex justify-center top-0'>
        <p className='text-4xl justify-center m-3'>Bayu Krisna</p> 
      </div>
      <div className='flex justify-center top-0'>
       <p className='justify-center m-3'> Junior Web Design</p>
      </div>
      <div>
      </div>
      <div>
        <p id='About Me'  className='text-4xl mx-4' >About Me</p>
        <p className='mx-4'>Selamat Pagi Bapak/Ibu  Sebelum memulainya saya mengucapkan terimakasih atas waktu yang diberikan,saat ini saya akan memperkenalkan diri terlebih dahulu, nama saya Ida Bagus Bayu Krisna Wibawa ,
        teman-teman saya biasa memanggil saya dengan sebutan Bayu.Saya juga memiliki hobi bermain game dan membaca atau menonton video tentang sistem tata surya,asli saya berasal dari Mengwi dan sekarang 
        saya tinggal/menetap di Denpasar Selatan ,Kuta. Dan saya sekarang berstatus sebagai siswa SMK,untuk perkenalan saya rasa sudah cukup dan terimakasih telah meluangkan waktu untuk membaca CV saya,
        dengan ini saya mengucapkan terimakasih dan selamat pagi.</p>
      </div>
      <div></div>
      <div></div>
      <div>
        <p id='Pendidikan'  className='text-4xl mx-4' >Pendidikan</p>
        <p className='mx-4'>Sekolah Dasar : SDN 3 Pedungan</p> 
          <div></div>
        <p className='mx-4'>SMP  	 	 	    : SMP Tunas Harapan Bangsa</p> 
          <div></div>
        <p className='mx-4'>SMK  	 	 	    : SMKTI Bali Global Denpasar</p> 
          <div></div>
      </div>
      <div></div>
      <div></div>
      <div>
        <p id='Keahlian'  className='text-4xl mx-4' >Keahlian</p>
        <p className='mx-4'>-HTML</p> 
        <div></div>
        <p className='mx-4'>-CSS</p>
        <div></div>
        <p className='mx-4'>-Bahasa Inggris</p> 
        <div></div>
      </div>
      <div></div>
      <div></div>
      <div>
        <p id='Contact'  className='text-4xl mx-4'>Contact</p>
        <p className='mx-4'>Email :Bayukrw8989@gmail.com</p>
        <div></div>
        <p className='mx-4'>No HP :081337558186</p>
      </div></nav>
      <footer className="h-16 md-m:text-white shadow-md bg-neutral-200 border-t z-20 border border-neutral-400 grid place-items-center" id="footer">
            <div className="container footer__container flex justify-center items-center font-normal opacity-75 text-sm">
                <p>Copyright © 2023 BayuKrisna909 . All rights reserved</p>
            </div>
        </footer>
    </main>
     </>
  )
}
